apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: ops
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 78.5.0
    helm:
      values: |
        fullnameOverride: kps
        grafana:
          adminPassword: "admin"  # change later or use a Secret
          service:
            type: NodePort
            nodePort: 30030
          persistence:
            enabled: false
          additionalDataSources:
            - name: Loki
              type: loki
              access: proxy
              url: http://loki-gateway.observability.svc.cluster.local
            - name: Tempo
              type: tempo
              access: proxy
              url: http://tempo.observability.svc.cluster.local:3100
        alertmanager:
          enabled: true
        prometheus:
          prometheusSpec:
            scrapeInterval: 30s
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: ["CreateNamespace=true"]
