apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ops-root
  namespace: argocd
spec:
  project: ops
  source:
    repoURL: https://github.com/wesleythorsen1/homelab.git
    targetRevision: k8s
    path: clusters/homelab/ops/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
