apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: ops
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo
    targetRevision: 1.23.3
    helm:
      values: |
        fullnameOverride: tempo
        tempo:
          storage:
            trace:
              backend: filesystem
          receivers:
            otlp:
              protocols:
                http:
                grpc:
        service:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated: { prune: true, selfHeal: true }
