apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ops
  namespace: argocd
spec:
  description: Apps deployed in the ops silo on cluster "homelab"
  sourceRepos:
    - https://github.com/wesleythorsen1/homelab
  destinations:
    - namespace: demo
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
