apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ops
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  description: Apps deployed in the ops silo on cluster "homelab"
  sourceRepos:
    - '*'
  destinations:
    - namespace: demo
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: observability
      server: https://kubernetes.default.svc
    - namespace: ci
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
