apiVersion: v1
kind: Service
metadata:
  name: {{ include "whoami.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "whoami.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
